### PR TITLE
Refactor modules and update code format.

### LINKED ISSUE #11: Refactoring modules
Hello - I’m wondering if I may contribute by refactoring some of your modules? I would like to make some functions more concise, and I’ll do my best to preserve the current module API.

### PR DESCRIPTION
**Pull request by irahorecka**
## Description
Refactor modules and update code format.

## Related Issue(s)
Fixes #11 

## User-facing Changes
None

## Screenshots (If necessary)
None

### CODE REVIEW

**Review by alec-kr — CHANGES_REQUESTED** [review]
image

A few linter errors are still present

**Comment by irahorecka** [comment]
Ok lemme fix this real quick

**Review by irahorecka — COMMENTED** [review]
Reviewed.

**Review by alec-kr — APPROVED** [review]
Seems okay. I will have to fix some of the the lines that are still too long, but this will be okay for now.

Thank you for your contribution :)

**Pull request merged**
