### PR TITLE
Added development tools

### PR DESCRIPTION
**Pull request by gauravkolekar**
Added most important development tools. No tool added for documentation

Issue link: [Decision on the development tools that will be used#22](https://github.com/alec-kr/F1PyStats/issues/22)

### CODE REVIEW

**Review by alec-kr — CHANGES_REQUESTED** [review]
Since you have removed the default ```setup.py```, you should update the README to include the new installation instructions.

You must also specify that poetry must be installed prior to attempting package installation.

**Comment by gauravkolekar** [comment]
> Since you have removed the default `setup.py`, you should update the README to include the new installation instructions.
> 
> You must also specify that poetry must be installed prior to attempting package installation.

My bad completely forgot on mentioning the new new way to install dependencies let me add that

**Review by alec-kr — CHANGES_REQUESTED** [review]
The README still needs some work:

- Remove the following line which states that users should install the dependencies manually:
```$ pip install pandas requests```

- The following line which uses pip to install the package must also be removed:
```$ pip install path/to/F1PyStats/```

**Review by alec-kr — APPROVED** [review]
Great job on implementing Poetry into the project. Thank you for contirbuting 😄.

**Pull request merged**
