### PR TITLE
Added Contributors section into main README.md

### LINKED ISSUE #81: Want to add Contributors section into main README.md
I think it looks cool and it will automatically updated whenever a contributor contribute to this project.

### PR DESCRIPTION
**Pull request by malay5**
## Description

Added Contributors section, showing all the contributors, who have contributed to the project

## Related Issue(s)

Fixes #81

### CODE REVIEW

**Comment by malay5** [comment]
Please close this issue under hacktoberfest22

**Comment by malay5** [comment]
I, by mistake added another PR, which was meant for another issue. Once this PR gets accepted, I will open another PR for another issue

**Comment by alec-kr** [comment]
Why was ```f1pystats.py``` removed? The current code cannot function without the main file.

**Review by alec-kr — CHANGES_REQUESTED** [review]
```f1pystats.py``` and ```__init__.py``` were removed for seemingly no reason.

Please fix.

**Comment by malay5** [comment]
I am really sorry, actually there was a mixup between two PRs I was trying to create, and they got merged in this single PR. I will update it asap

**Comment by malay5** [comment]
I will create a new PR, inorder to make it more clean, please excuse me

**Pull request closed without merging**
