### PR TITLE
Introduce flake8 style guide checker

### PR DESCRIPTION
**Pull request by SilverTux**
## Description

Flake8 is a tool for checking if the code formatted correctly. It is good to have a coding style convention for a project and using flake8 is easy and popular among python projects.

## Related Issue(s)

No issue for this

### CODE REVIEW

**Comment by SilverTux** [comment]
After creating the PR I've realized that the #72 PR doing something similar but without introducing flake8. I can remove the parts which is already in #72 leaving only the flake8 parts of this PR

**Comment by alec-kr** [comment]
Hey welcome to F1PyStats. Thank you for making your first PR to this repository 😁

**Comment by alec-kr** [comment]
#72 has fixed the outstanding linting issues, but you have also implemented the ```flake8``` checker which will automatically detect these errors for us. This is good work!

**Review by alec-kr — APPROVED** [review]
I will merge your changes, since you've added the flake8 functionality to the repository, which is something that was needed.

Thank you for contributing :)

**Comment by SilverTux** [comment]
> I will merge your changes, since you've added the flake8 functionality to the repository, which is something that was needed.
> 
> Thank you for contributing :)

Thank You for merging it! :)

**Pull request merged**
