### PR TITLE
Created Logo for Library

### PR DESCRIPTION
**Pull request by Glowstik-YT**
## Description
Using photoshop and f1 assets, I was able to create two versions of logos for the library. I created an assets folder to put them in to better organize the logos. I felt as if a logo would be needed for documentation or to represent the library in some way.

### CODE REVIEW

**Comment by Glowstik-YT** [comment]
Well according to this F1's official guidelines, https://www.formula1.com/en/toolbar/guidelines.html, it is ok for fans to use as long as it is for nonprofit use. Although I can gladly create a version without their logo if you still feel it's necessary.

**Comment by alec-kr** [comment]
According to the link you sent me, they state that the logo or any derivatives cannot be used to create personal logos. (Fans NOT excluded from this rule)
image

Once again, they also make it clear to us that we must NOT use their logos. They also state that we must not integrate their marks into other marks.
image

Based on these statements, I think it is safe to say that we should not use the official F1 logo in our repo. 

We can keep the photo of the F1 car as the background, but the logo will have to be removed apparently.

NOTE: This is my understanding of the guidelines. If you think I am misinterpreting this, please let me know.

**Comment by Glowstik-YT** [comment]
Alright, I updated the logos and replaced the f1 logo with the car, the downside to this although is that there is only one version of the logo...

**Review by alec-kr — APPROVED** [review]
Neat work. Looks great.

Merging now.

**Comment by alec-kr** [comment]
I will add the image as our social media preview

**Pull request merged**
