### PR TITLE
Create bagusarya.html

### PR DESCRIPTION
**Pull request by BagusAryadita**
merge pls hehe

### CODE REVIEW

**Comment by SilverTux** [comment]
Hi @BagusAryadita 
How is this PR related to the project?

**Comment by mathieu-lemay** [comment]
It's, not. The guy is a spammer.

For example:
https://github.com/mnosov622/todo-list/pull/24
https://github.com/aloner-pro/Steno/pull/7
https://github.com/thesarthakjain/telegram_bot/pull/4
https://github.com/unnikrishnan2002/Narrow-Links/pull/34
https://github.com/aeternity/superhero-wallet/pull/1639

**Comment by alec-kr** [comment]
Thank you for pointing that out @mathieu-lemay.

**Comment by alec-kr** [comment]
Marked as spam, and closing the PR.

**Pull request closed without merging**
