### PR TITLE
Added Linting, Type Checking and Documentation

### PR DESCRIPTION
**Pull request by gauravkolekar**
## Description

- `.darglint` file created, it is a documentation linter
- `.flake8` file created will all the configuration
- `flake8.yml` created under `../.github/workflows` which will run liniting on all push
- `docs/conf.py` created to for the documentation build
- `index.rst` created with placeholder text
- `reference.rst` create for future purposes
- `mypy.ini` created with configuration for the mypy package
- `noxfile.py` updated with all the tasks that require automation
- `pyproject.yml` updated with new `dev` dependencies

## Related issue
[https://github.com/alec-kr/F1PyStats/issues/22](https://github.com/alec-kr/F1PyStats/issues/22)

## User facing changes
None

### CODE REVIEW

**Comment by alec-kr** [comment]
There a some redundant additions in this PR.

- There is already a test folder added to the master branch of the repo, containing tests for each module.
- Linting is already on the master branch of the repo. 

The tests and linting has already been added to this repo's workflow. Looking at the branch you are trying to merge, it appears as though you have not updated your branch with the latest changes, hence we have these issues.

**Review by alec-kr — CHANGES_REQUESTED** [review]
We already implemented pylint in the repository, so I doubt we should merge flake8, and any related files. (```.flake8```, ```worflows/.flake8.yml```)

Good idea on adding documentation tools!

Your tests folder clearly is out-of-date with the master branch. All tests and workflow has already been made. (This should probably be removed 🤷🏽‍♂️)

If you think I'm overlooking something, please let me know :)

**Comment by alec-kr** [comment]
The switch to flake8 would be best if done in a separate PR. Other than that, you have done some great work here!

I will merge it shortly

**Review by alec-kr — APPROVED** [review]

**Comment by alec-kr** [comment]
Pylint doesn't seem happy. Maybe you should review the errors first

**Review by alec-kr — CHANGES_REQUESTED** [review]
Pylint doesn't seem happy. Maybe you should correct the errors first

**Comment by gauravkolekar** [comment]
> Pylint doesn't seem happy. Maybe you should correct the errors first

I going to add noxfile to the pylint ignore list. Since it is not really part of the package. I'll also delete the flake8 github workflow I created as part of this change.

**Review by alec-kr — CHANGES_REQUESTED** [review]
These are some great changes. Thank you for contributing 😁 

One small issue: You mentioned that flake8 was removed from your GitHub workflow. However, a ```.flake8``` file is still present in the root of the repository. 

Your PR should be ready to merge after this change :)

**Comment by gauravkolekar** [comment]
I plan to keep the `.flake8` file. I deleted the `.github/workflows/flake8.yml`. In future I plan to really build out the linting capability using `flake8`. Github workflow will keep using the the pylint action you build.

**Comment by gauravkolekar** [comment]
> These are some great changes. Thank you for contributing 😁
> 
> One small issue: You mentioned that flake8 was removed from your GitHub workflow. However, a `.flake8` file is still present in the root of the repository.
> 
> Your PR should be ready to merge after this change :)

I plan to keep the .flake8 file. I deleted the .github/workflows/flake8.yml. In future I plan to really build out the linting capability using flake8. Github workflow will keep using the the pylint action you build.

**Review by alec-kr — APPROVED** [review]
All good. Merging this now.

Thank you for your contribution :)

**Pull request merged**
