### PR TITLE
ci: Use Poetry for CI

### LINKED ISSUE #85: Use Poetry in CI
**Is your feature request related to a problem? Please describe.**
Since Poetry is being used for dependency and virtualenv management in this project, it should also be used in CI to ensure that contributors' changes meet the required checks, and so CI matches the developer loop as closely as possible.

**Describe the solution you'd like**
Use snok's Install Poetry action for setup and follow the [example](https://github.com/marketplace/actions/install-poetry-action#testing) for setting up a workflow to invoke tests in CI.

**Describe alternatives you've considered**
The existing CI references `requirements.txt`, which isn't being used for dependency management. It also "manually" installs each dependency, rather than using the pinned versions in `pyproject.toml`.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by jidicula**
## Description

Installs Poetry and uses it for dependency setup and virtualenv execution in CI. If nothing has changed in the lockfile, use cached virtual environment.

See https://github.com/marketplace/actions/install-poetry-action#testing for an example workflow that I adapted for this project.

## Related Issue(s)

Fixes #85 

## User-facing Changes

N/A

## Screenshots (If necessary)

N/A

### CODE REVIEW

**Comment by jidicula** [comment]
@alec-kr This is also a Hacktoberfest PR - if it passes muster, could you add the `hacktoberfest-accepted` label to this PR?

**Comment by alec-kr** [comment]
For some reason, the python package test is now stalled when doing the flake8 test. 
Screenshot from 2022-10-27 23-28-13

As you can see in the screenshot above, flake8 is running for an indefinite period. 

Do you think some of the changes made in ```python_package.yml``` would have resulted in this issue?

**Comment by jidicula** [comment]
I think I need to add `.venv` to flake8's ignore config. I'll update my PR.

**Comment by alec-kr** [comment]
The previous issue was fixed.

However, there is a new error in the test:
Screenshot from 2022-10-28 12-27-47

**Comment by jidicula** [comment]
> The previous issue was fixed. Great work!
> 
> However, there is a new error in the test :( Screenshot from 2022-10-28 12-27-47

Looks like `pytest-cov` isn't included in `pyproject.toml`. I'll add it.

**Comment by jidicula** [comment]
@alec-kr can you approve the workflows again? I've pushed up a commit updating the Poetry manifests.

**Comment by youpong** [comment]
> Looks like `pytest-cov` isn't included in `pyproject.toml`. I'll add it.

Thank you for that.  I should add it in #71.

**Comment by alec-kr** [comment]
Excellent work! Thank you for contributing to the repo.

I will merge your changes now.

**Review by alec-kr — APPROVED** [review]

**Pull request merged**
