### PR TITLE
Refactory of the code

### PR DESCRIPTION
**Pull request by Domefemia**
I have changed all the string manipulation with f string, and all the function that return a list of element into list comprehension, making them a little faster.

### CODE REVIEW

**Comment by alec-kr** [comment]
Excellent work! Thanks for contributing 😁. 

I will review the changes shortly.

**Review by alec-kr — CHANGES_REQUESTED** [review]
In ```driver_results.py```, you have refactored ```get_driver_names()``` and removed the for loop that was used to get each driver name. This is good!

```driver_results.py```
fixed

However, in ```race_winners.py```, you have not made this change. The for loop is still there, as seen below:

```race_winners.py```
not-fixed

Can you kindly update ```race_winners.py``` to reflect the change you made in ```driver_results.py```? 

Everything else in this PR is great, and ready to merge!

**Comment by Domefemia** [comment]
I have done it

**Review by alec-kr — CHANGES_REQUESTED** [review]
Line 7 of ```race_winners.py``` now contains a syntax error:

Screenshot from 2022-09-22 12-19-13

**Comment by Domefemia** [comment]
Solved

**Comment by Domefemia** [comment]
Yes that's because I'm dumb and I have removed the brackets because I trought I added them by mistake

**Comment by Domefemia** [comment]
Tested them and all of the functions are working fine

**Comment by alec-kr** [comment]
> Yes that's because I'm dumb and I have removed the brackets because I trought I added them by mistake

It happens to all of us at some point. The main thing is that you resolved the issue 💪🏽

**Comment by alec-kr** [comment]
Thanks a lot for submitting your PR. Feel free to have a look at the outstanding [issues](https://github.com/alec-kr/F1PyStats/issues).

At the moment, I would like to further refactor the code to implement some Object-Oriented programming practices (classes, objects, etc.). If you can help with this, it would be great!

**Pull request merged**
