### PR TITLE
Standardize code format and modularize certain functions

### LINKED ISSUE #11: Refactoring modules
Hello - I’m wondering if I may contribute by refactoring some of your modules? I would like to make some functions more concise, and I’ll do my best to preserve the current module API.

### PR DESCRIPTION
**Pull request by irahorecka**
## Description
Standardized code format and modularized certain functions. Cleaner for reading and nicer logic flow. API was not changed.

## Related Issue(s)
Fixes #11 

## User-facing Changes
None

## Screenshots (If necessary)
None

### CODE REVIEW

**Review by alec-kr — CHANGES_REQUESTED** [review]
These are some good ideas implemented. However, some of the changes you made to the lines has caused Pylint to throw several errors. 

The Python lists were split on several lines to prevent long lines. You have placed each list on a single line, causing the linter to throw these errors. These long lines are against the PEP8 style guide.

You also put some of the multi-line import statements on a single line. This is also against the PEP8 standards.

**Comment by irahorecka** [comment]
Ok

**Review by alec-kr — CHANGES_REQUESTED** [review]
All GitHub tests are now failing :(

Your fork of the repo does not seem to be up-to-date with the current main branch.

The ```f1pystats.py``` on your fork does not have the ```finishing_status``` function. You might also have to do some work on that function. Before requesting another review.

Please run ```git pull``` to update your local repo, and ensure you test your changes before submitting another PR.

**Comment by alec-kr** [comment]
Note to viewers: This PR was reopened by the author in #49, and merged shortly after.

**Pull request closed without merging**
