### PR TITLE
Added a function  to get fastest lap based on the input year and race round

### LINKED ISSUE #76: Add function to get fastest laps
I want to add a method that generates the fastest lap, and the respective driver for a given race.

### PR DESCRIPTION
**Pull request by malay5**
## Description
I have written a function to get the fastest lap for the particular year and particular round, which can be called like

fp.fastest_laps(year=2020,race_round=1)

I have also added  a function, to convert the hh:mm.ss to seconds using _get_sec, as it might be needed for future enhancements.

## Related Issue(s)

Fixes #76

### CODE REVIEW

**Comment by malay5** [comment]
Please close this PR under hacktoberfest

**Comment by malay5** [comment]
The code functions are fine, but the checks are failing. Can someone pls. help

**Comment by youpong** [comment]
The indentation of the following lines is seemed to be too deep.
Try making them shallower.

- line 430 of f1pystats.py
- line 434 of f1pystats.py

**Comment by youpong** [comment]
L.430 seems to have worked. Just one more step.

**Comment by youpong** [comment]
L.434 should be indented the same as L.430.

**Comment by malay5** [comment]
> L.434 should be indented the same as L.430.

Resolved! Thanks a lot!

**Comment by malay5** [comment]
Can you please add hacktober label to this PR?

**Comment by malay5** [comment]
Can you please add hacktober label to this PR?

**Comment by malay5** [comment]
> Good function implementation.
> 
> However, you have not added any tests to your code. You should include tests when adding a new function/method to the repo.
> 
> Please add a test file called `test_fastest_laps.py` in [/package_tests](https://github.com/alec-kr/F1PyStats/tree/main/tests/package_tests), which evaluates the results of the `fastest_laps` function.
> 
> You can have a look at other files within the [/package_tests](https://github.com/alec-kr/F1PyStats/tree/main/tests/package_tests) directory, to get an idea how the tests should be written.

I have added the package tests.
Can you please add hacktober label to this PR

**Review by alec-kr — CHANGES_REQUESTED** [review]
You must also add the new function to the README.

**Comment by alec-kr** [comment]
> Can you please add hacktober label to this PR?
The label will be added once the PR is accepted.

**Comment by alec-kr** [comment]
@malay5 Are you making any progress on the issue?

**Comment by alec-kr** [comment]
Update: Since this PR's author has been inactive, the PR has been succeeded by #96.

#96 is now merged to the ```main``` branch, so this PR will be closed.

**Pull request closed without merging**
